# This file is part of BOINC.
# https://boinc.berkeley.edu
# Copyright (C) 2025 University of California
#
# BOINC is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License
# as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
#
# BOINC is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with BOINC.  If not, see <http://www.gnu.org/licenses/>.

name: Build .NET Solution

on:
  push:
    branches: [ master ]
    tags: [ v*.*.* ]
  pull_request:
    branches: [ master ]


concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  AZURE_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
  AZURE_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
  AZURE_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
  AZURE_ENDPOINT: ${{secrets.AZURE_ENDPOINT}}
  AZURE_CODE_SIGNING_NAME: ${{secrets.AZURE_CODE_SIGNING_NAME}}
  AZURE_CERT_PROFILE_NAME: ${{secrets.AZURE_CERT_PROFILE_NAME}}
  TSCT: ${{github.workspace}}\temp\TSCT
  DLIB: ${{github.workspace}}\temp\TSCT\Microsoft.Trusted.Signing.Client\bin\x64\Azure.CodeSigning.Dlib.dll
  DMDF: ${{github.workspace}}\metadata.json

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Install Trusted Signing Client Tools
        if: startsWith(github.ref, 'refs/tags/') && env.AZURE_CLIENT_ID != 0 && env.AZURE_CLIENT_SECRET != 0 && env.AZURE_TENANT_ID != 0 && env.AZURE_ENDPOINT != 0 && env.AZURE_CODE_SIGNING_NAME != 0 && env.AZURE_CERT_PROFILE_NAME != 0
        run: nuget.exe install Microsoft.Trusted.Signing.Client -Version 1.0.60 -x -OutputDirectory "${{ env.TSCT }}"

      - name: Write metadata.json
        if: startsWith(github.ref, 'refs/tags/') && env.AZURE_CLIENT_ID != 0 && env.AZURE_CLIENT_SECRET != 0 && env.AZURE_TENANT_ID != 0 && env.AZURE_ENDPOINT != 0 && env.AZURE_CODE_SIGNING_NAME != 0 && env.AZURE_CERT_PROFILE_NAME != 0
        run: python ./create_signing_metadata.py "${{ env.DMDF }}" "${{ env.AZURE_ENDPOINT }}" "${{ env.AZURE_CODE_SIGNING_NAME }}" "${{ env.AZURE_CERT_PROFILE_NAME }}"

      - name: Build solution (Release)
        run: msbuild boinc-buda-runner-wsl-installer.sln /p:Configuration=Release /p:DLIB=${{ env.DLIB }} /p:DMDF=${{ env.DMDF }}

      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: boinc-buda-runner-wsl-installer
          path: ${{github.workspace}}/bin/Release/boinc-buda-runner-wsl-installer.exe
